language: node_js

script:
  - 'npm run coverage'

notifications:
  slack:
    rooms: ['laiapp:ogJ1E68zuYx9lcDG3o9Yq9av#rn-ci']
    on_start: never
    on_success: always
    on_failure: always

after_success:
  - 'npm run coveralls'

branches:
  only:
    - /^master$/
